# Generated by Django 5.2.1 on 2025-05-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(max_length=1)),
                ('idproveedor', models.IntegerField()),
            ],
            options={
                'db_table': 'regprovs_user',
                'managed': False,
            },
        ),
    ]
